### ISSUE TITLE
Auto save on overworld

### ISSUE THREAD

**Issue by ReflextionsDev** [ReflextionsDev/Zombiehood#85] opened 2024-08-06 16:25 UTC
In case players close without pressing save and exit

**Comment by ReflextionsDev** [comment] 2024-08-18 23:52
Just run the save function on overworld start after a few seconds, button will be mostly cosmetic

**Comment by Everade** [comment] 2024-08-19 19:54
I conducted several tests, and everything seems to be working as intended. It turns out my initial report was incorrect. Progress is only lost if you exit the game while in the middle of a level, which is expected behavior. The game already saves automatically when you finish a level and in several other situations.

To improve the user experience, it might be helpful to add an exit button that returns players to the menu without closing the game. In that case, we could include a warning that run progress will be lost.

During my debugging, I implemented a saving indicator, which I think would be useful for players as well. So I polished it a bit, as it should help prevent players from closing the game while it's saving and provide helpful information overall.

https://github.com/ReflextionsDev/Zombiehood/pull/109

**Closed by Everade** 2024-08-19 19:54 UTC
Labels: feature
